"use client";
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "./COMMON/Sidebar";
import Navbar from "./COMMON/Navbar";
import React, { useState } from "react";
import { usePathname } from "next/navigation";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const pathname = usePathname();
  const isLoginPage = pathname === "/login";

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {!isLoginPage && <Sidebar open={sidebarOpen} setOpen={setSidebarOpen} />}
        <div className={!isLoginPage ? "md:ml-55" : ""}>
          {!isLoginPage && (
            <Navbar sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} />
          )}
          <main className={!isLoginPage ? "pt-[56px] min-h-screen" : "min-h-screen"}>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
